sudo: required
services: -docker

before_install:
  - docker build -t kmltriggy/react-test -f ./client/Dockerfile.dev
script:
  - docker run kmltriggy/react-test npm test -- --coverage

after_success:
  - docker build -t kmltriggy/multi-client ./client
  - docker build -t kmltriggy/multi-nginx ./nginx
  - docker build -t kmltriggy/multi-server ./server
  - docker build -t kmltriggy/multi-worker ./worker

  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take those image and push to docker-hub
  - docker push kmltriggy/multi-client
  - docker push kmltriggy/multi-nginx
  - docker push kmltriggy/multi-server
  - docker push kmltriggy/multi-worker
